version: '2'

services:
  registry:
    image: registry:2
    container_name: registry
    restart: always
    ports:
      - "5000:5000"
    environment:
      - SEARCH_BACKEND=sqlalchemy

  registry-ui:
    image: konradkleine/docker-registry-frontend:v2
    container_name: registry-ui
    ports:
      - "80:80"
    environment:
      - ENV_DOCKER_REGISTRY_HOST=192.168.99.101
      - ENV_DOCKER_REGISTRY_PORT=5000
    depends_on:
      - registry
