version: '2'

services:
  web-ui:
    image: ${ENV_DOCKER_REGISTRY_HOST}:5000/hq/client-ui
    networks:
      - frontend
    ports:
      - "80:80"
    environment:
      - "constraint:capacity==ui"

  discovery:
    image: ${ENV_DOCKER_REGISTRY_HOST}:5000/hq/discovery
    hostname: discovery
    networks:
      - backend
    environment:
      - "constraint:capacity!=activity-service"
    ports:
      - "8761:8761"

  admin:
    image: ${ENV_DOCKER_REGISTRY_HOST}:5000/hq/admin
    hostname: admin
    networks:
      - backend
    environment:
      - "constraint:capacity!=activity-service"
    ports:
      - "8081:8081"

  activity:
    image: ${ENV_DOCKER_REGISTRY_HOST}:5000/hq/activity
    hostname: activity
    networks:
      - backend
    ports:
      - "8080:8080"
    environment:
      - "constraint:capacity==activity-service"
#  dns:
#    image: phensley/docker-dns
#    container_name: dns
#    domainname: horoquartz.poc
#    networks:
#      - backend
#    volumes:
#      - "192.168.99.106/docker.sock"

networks:
  frontend:
    driver: overlay
  backend:
    driver: overlay
