server:
  port: ${server.port}

spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    hostname: localhost
  client:
    registryFetchIntervalSeconds: 5
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  profiles: cloud

eureka:
  instance:
    hostname: activity
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
