server:
  port: 8080

spring:
  application:
    name: activity
  cloud:
    config:
      enabled: false
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    hostname: localhost
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  profiles: cloud
  cloud:
    config:
      enabled: true

eureka:
  instance:
    hostname: activity
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
