server:
  port: 8080

info:
  version: 1.0-SNAPSHOT

spring:
  application:
    name: activity-services
  cloud:
    config:
      enabled: false

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
