INSERT INTO EMPLOYEE (EID) VALUES ('000002'), ('000003'), ('000004');
INSERT INTO PROJECT (NAME, START_DATE) VALUES ('POC Architecture', PARSEDATETIME('29-02-2016','dd-mm-yyyy'));
INSERT INTO ACTIVITY (PROJECT_ID, NAME, EVENT_TYPE) VALUES (1, 'Pilotage', 'IMPUTATION');
INSERT INTO ACTIVITY (PROJECT_ID, NAME, EVENT_TYPE) VALUES (1, 'Réalisation', 'IMPUTATION');
INSERT INTO ACTIVITY_RECORD (EMP_ID, ACTIVITY_ID, DATE, DURATION) VALUES (1, 2, PARSEDATETIME('2016-02-29 17:54:33','yyyy-mm-dd hh:mm:ss'), 0.5);
INSERT INTO ACTIVITY_RECORD (EMP_ID, ACTIVITY_ID, DATE, DURATION) VALUES (1, 2, PARSEDATETIME('2016-03-01 18:04:20','yyyy-mm-dd hh:mm:ss'), 1.0);
INSERT INTO ACTIVITY_RECORD (EMP_ID, ACTIVITY_ID, DATE, DURATION) VALUES (1, 2, PARSEDATETIME('2016-03-02 17:55:31','yyyy-mm-dd hh:mm:ss'), 0.75);
INSERT INTO ACTIVITY_RECORD (EMP_ID, ACTIVITY_ID, DATE, DURATION) VALUES (1, 2, PARSEDATETIME('2016-03-03 17:56:58','yyyy-mm-dd hh:mm:ss'), 0.5);
INSERT INTO ACTIVITY_RECORD (EMP_ID, ACTIVITY_ID, DATE, DURATION) VALUES (1, 1, PARSEDATETIME('2016-03-04 18:02:26','yyyy-mm-dd hh:mm:ss'), 0.25);

INSERT INTO PRODUCT (PRODUCT_NUMBER, NAME, CATEGORY, PRICE) VALUES ('PN-P0001', 'Product #1', 'Category #1', 20.45);
INSERT INTO PRODUCT (PRODUCT_NUMBER, NAME, CATEGORY, PRICE) VALUES ('PN-P0002', 'Product #2', 'Category #1', 50.00);
INSERT INTO PRODUCT (PRODUCT_NUMBER, NAME, CATEGORY, PRICE) VALUES ('PN-P0003', 'Product #3', 'Category #2', 25.75);
INSERT INTO PRODUCT (PRODUCT_NUMBER, NAME, CATEGORY, PRICE) VALUES ('PN-P0004', 'Product #4', 'Category #2', 120.90);
INSERT INTO PRODUCT (PRODUCT_NUMBER, NAME, CATEGORY, PRICE) VALUES ('PN-P0005', 'Product #5', 'Category #2', 86.70);
INSERT INTO PRODUCT (PRODUCT_NUMBER, NAME, CATEGORY, PRICE) VALUES ('PN-P0006', 'Product #6', 'Category #3', 45.35);
INSERT INTO PRODUCT (PRODUCT_NUMBER, NAME, CATEGORY, PRICE) VALUES ('PN-P0007', 'Product #7', 'Category #3', 80.20);
