server:
  port: ${server.port}

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    hostname: localhost
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  profiles: cloud

eureka:
  instance:
    hostname: admin
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
