server:
  port: 8081

spring:
  application:
    name: administration-console
  cloud:
    config:
      enabled: false

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    hostname: localhost
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  profiles: cloud
  cloud:
    config:
      enabled: true

eureka:
  instance:
    hostname: admin
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
