server:
  port: 8081

info:
  version: 1.0-SNAPSHOT

spring:
  application:
    name: administration-console
  cloud:
    config:
      enabled: false

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/