server:
  port: ${server.port}

# standalone server config
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
    server:
      waitTimeInMsWhenSyncEmpty: 0

---
spring:
  profiles: cloud

eureka:
  instance:
    hostname: discovery
  client:
    serviceUrl:
      defaultZone: http://discovery:${server.port}/eureka/
